name: Build Docker file to gcr.io

on:
  pull_request:
    branches:
      - master

jobs:
#   prepare-npm-repo:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout the repo
#         uses: actions/checkout@v2

#       # test

  build_and_push:
#     needs: prepare-npm-repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_email: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud config set account github-action &
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build Image
        run: |
          docker build -t gcr.io/stumpark-blog/frontend:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push gcr.io/stumpark-blog/frontend:${{ github.sha }}
      - name: cloud run deploy
        run: |
          gcloud run deploy frontend \
            --image gcr.io/stumpark-blog/frontend:${{ github.sha }} \
            --region asia-northeast1 \
            --platform managed \
            --project stumpark-blog
