name: GCR container Health Cherk job

on:
  schedule:
    # every 30 min , curl to SERVER
    - cron: '*/15 * * * *'

jobs:
  Curl-to-Frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Curl
        run: curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0" https://blog.stumpark.com
